spring.application.name=gestion-pedidos-backend
# MongoDB Configuration
spring.data.mongodb.uri=${URI_MONGODB}

# PostgreSQL Configuration

spring.r2dbc.url=r2dbc:postgresql://34.171.188.241:5432/pedido
spring.r2dbc.username=${PG_USERNAME}
spring.r2dbc.password=${PG_PASSWORD}
spring.log.level.org.springframework=INFO

#spring.datasource.url=${PG_DATASOURCE}
#spring.datasource.username=${PG_USERNAME}
#spring.datasource.password=${PG_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect